version: '3.6'

services:

  postgres:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - TZ=UTC
      - PGTZ=UTC
      - POSTGRES_DB=nwp
      - POSTGRES_USER=nwp_user
      - POSTGRES_PASSWORD=password

volumes:
  db_data:
